package Views;

import Controllers.AgendaDAO;
import Controllers.DataBaseConnector;
import Controllers.DiagnosticoDAO;
import Views.SignosVitales;
import Views.Expediente_Clinico;
import Views.VistaImpresion;

/**
 *
 * @author Miguel
 */
public class Consulta extends javax.swing.JFrame {

 
      PrescripccionMedica vistaReceta;
      Examenes_Laboratorio examenesView;
      Agenda agenda;
      SignosVitales signosVitales;
      Diagnosticos diagnosticoView;
      Expediente_Clinico expClinico;
      Inicio inicio;
      
      StringBuilder diagnostico;
      StringBuilder laboratorios;
      StringBuilder receta;
      
      String recetasId;
      String examenesId;
      String diagnosticoId;
      String agendaId;
      
    public Consulta() {
        initComponents();
        planField.setEditable(false);
        analiticoTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datosPaciente2 = new Views.DatosPaciente();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjetivoText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        objetivoTxt = new javax.swing.JTextArea();
        diagnosticoBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        analiticoTxt = new javax.swing.JTextArea();
        signosVitalesBtn = new javax.swing.JButton();
        expedienteBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        planField = new javax.swing.JTextArea();
        guardarCnsultaBtn = new javax.swing.JButton();
        imprimirBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        examenesBtn = new javax.swing.JButton();
        recetaBtn = new javax.swing.JButton();
        agendarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta Externa");

        subjetivoText.setColumns(20);
        subjetivoText.setRows(5);
        jScrollPane1.setViewportView(subjetivoText);

        objetivoTxt.setColumns(20);
        objetivoTxt.setRows(5);
        jScrollPane2.setViewportView(objetivoTxt);

        diagnosticoBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\diagnostico.png")); // NOI18N
        diagnosticoBtn.setText("DIAGNOSTICO");
        diagnosticoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        diagnosticoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosticoBtnActionPerformed(evt);
            }
        });

        analiticoTxt.setColumns(20);
        analiticoTxt.setRows(5);
        jScrollPane3.setViewportView(analiticoTxt);

        signosVitalesBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        signosVitalesBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\signosVitales.png")); // NOI18N
        signosVitalesBtn.setText("SIGNOS VITALES");
        signosVitalesBtn.setAlignmentY(0.6F);
        signosVitalesBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signosVitalesBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        signosVitalesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signosVitalesBtnActionPerformed(evt);
            }
        });

        expedienteBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\expedienteClinico.png")); // NOI18N
        expedienteBtn.setText("EXPEDIENTE CLINICO");
        expedienteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        expedienteBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        expedienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expedienteBtnActionPerformed(evt);
            }
        });

        planField.setColumns(20);
        planField.setRows(5);
        jScrollPane4.setViewportView(planField);

        guardarCnsultaBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\editar.png")); // NOI18N
        guardarCnsultaBtn.setText("CONCLUIR CONSULTA");
        guardarCnsultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCnsultaBtnActionPerformed(evt);
            }
        });

        imprimirBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\imprimir.png")); // NOI18N
        imprimirBtn.setText("IMPRIMIR CONSULTA");
        imprimirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBtnActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancelar.png"))); // NOI18N
        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUBJETIVO");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setBackground(new java.awt.Color(51, 0, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OBJETIVO");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(23, 23, 23))
        );

        panel3.setBackground(new java.awt.Color(0, 0, 153));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ANALIÍTICO");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel4.setBackground(new java.awt.Color(0, 0, 153));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PLANES");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        examenesBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\laboratorio.png")); // NOI18N
        examenesBtn.setText("EXAMENES");
        examenesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examenesBtnActionPerformed(evt);
            }
        });

        recetaBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\recetar.png")); // NOI18N
        recetaBtn.setText("RECETAR");
        recetaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recetaBtnActionPerformed(evt);
            }
        });

        agendarBtn.setIcon(new javax.swing.ImageIcon("C:\\gitRepos\\TESIS\\SSU-LPS\\SSU\\src\\Resources\\nuevaConsulta.png")); // NOI18N
        agendarBtn.setText("AGENDAR");
        agendarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agendarBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agendarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guardarCnsultaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(imprimirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(diagnosticoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(examenesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(recetaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 747, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3)))
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agendarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(signosVitalesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(expedienteBtn)
                                .addGap(44, 44, 44))))
                    .addComponent(datosPaciente2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(datosPaciente2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(examenesBtn)
                            .addComponent(recetaBtn)
                            .addComponent(diagnosticoBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signosVitalesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(expedienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(agendarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCnsultaBtn)
                    .addComponent(imprimirBtn)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        examenesBtn.getAccessibleContext().setAccessibleName("LabButton");
        recetaBtn.getAccessibleContext().setAccessibleName("recetar\\Btn");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signosVitalesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signosVitalesBtnActionPerformed
        if(signosVitales==null){
             signosVitales = new SignosVitales();
        }
        signosVitales.setVisible(true);
        signosVitales.setPaciente(datosPaciente2.getPaciente() );
        System.out.println("  " + datosPaciente2.getPaciente().getPrimerNombre() );
        
    }//GEN-LAST:event_signosVitalesBtnActionPerformed

    private void imprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBtnActionPerformed
        // TODO add your handling code here:
        VistaImpresion impresion = new VistaImpresion();
        impresion.setVisible(true);
        
    }//GEN-LAST:event_imprimirBtnActionPerformed

    private void expedienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expedienteBtnActionPerformed
        
        if(expClinico==null)
               expClinico = new Expediente_Clinico();
        
        expClinico.setVisible(true);
        expClinico.setBeneficiarioId(datosPaciente2.getPaciente());
    }//GEN-LAST:event_expedienteBtnActionPerformed

    private void diagnosticoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosticoBtnActionPerformed
       if(diagnosticoView==null)
            diagnosticoView = new Diagnosticos();
        diagnosticoView.setVisible(true);
        diagnosticoView.setConsulta(this);
    }//GEN-LAST:event_diagnosticoBtnActionPerformed

    
    //Evento en el boton para salir de la vista     
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           this.setVisible(false);
           this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    
    public void fillDiagnostico(String diagnostico){
        this.diagnostico=new StringBuilder( diagnostico);
        analiticoTxt.append(diagnostico);
    }
    
    public void fillPlanReceta(String recetas){
            planField.append(recetas);
    }
    public void fillPlanExamenes(String examenes){
            planField.append(examenes);
    }
    //evento para desplegar la vista de examenes de laboratorio
    private void examenesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examenesBtnActionPerformed
        if(examenesView==null)
            examenesView=new Examenes_Laboratorio();
        examenesView.setVisible(true);
        examenesView.setConsulta(this);
        examenesView.setBeneficiario(datosPaciente2.getPaciente());
    }//GEN-LAST:event_examenesBtnActionPerformed

    private void recetaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recetaBtnActionPerformed

       if(vistaReceta==null){ 
            vistaReceta = new PrescripccionMedica();  
       }
        vistaReceta.setVisible(true);
        vistaReceta.setConsulta(this);
        vistaReceta.limpiarVista();
        vistaReceta.setPaciente(datosPaciente2.getPaciente());
        
    }//GEN-LAST:event_recetaBtnActionPerformed

    private void agendarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarBtnActionPerformed
        if(agenda==null){
            agenda=new Agenda();
        }
        agenda.setVisible(true);
        agenda.setLocation(this.getWidth()/2, this.getHeight()/2);
        agenda.getData(datosPaciente2.getPaciente());
    }//GEN-LAST:event_agendarBtnActionPerformed

    private void guardarCnsultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCnsultaBtnActionPerformed

        String valores[] = new String[5];
        valores[0]= subjetivoText.getText();
        valores[1]=objetivoTxt.getText();
        valores[2]=analiticoTxt.getText();
        valores[3] = planField.getText();
        valores[4]= datosPaciente2.getPaciente().getID();        
        System.out.println(valores[0]);
        System.out.println(valores[1]);
        System.out.println(valores[2]);
        System.out.println(valores[3]);
        System.out.println(valores[4]);
        
        DiagnosticoDAO.guardarDiagnostico(valores[0],valores[1],valores[2],valores[3],valores[4]);
        
        AgendaDAO.actualizarConsulta(agendaId);
        inicio.actualizarConsulta();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_guardarCnsultaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    
    
    public DatosPaciente getDatosPacientes(){return this.datosPaciente2;}
    public void setAgendaId(String id){this.agendaId=id;}
    public void setInicio(Inicio inicio) {this.inicio = inicio;} 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendarBtn;
    private javax.swing.JTextArea analiticoTxt;
    private Views.DatosPaciente datosPaciente2;
    private javax.swing.JButton diagnosticoBtn;
    private javax.swing.JButton examenesBtn;
    private javax.swing.JButton expedienteBtn;
    private javax.swing.JButton guardarCnsultaBtn;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea objetivoTxt;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JTextArea planField;
    private javax.swing.JButton recetaBtn;
    private javax.swing.JButton signosVitalesBtn;
    private javax.swing.JTextArea subjetivoText;
    // End of variables declaration//GEN-END:variables
}
